IF TYPE_ID(N'SODTLDOCCHECKLIST') IS NOT NULL
DROP TYPE SODTLDOCCHECKLIST
GO

CREATE TYPE [dbo].[SODTLDOCCHECKLIST] AS TABLE(
	[CUSTNMBR] [char](15) NOT NULL,
	[DOCNUMBR] [char](21) NOT NULL,
	[DSCRIPTN] [char](31) NOT NULL,
	[QUANTITY] [numeric](19, 5) NOT NULL,
	[LNITMSEQ] [int] NOT NULL,
	[CMS_SELECTED] [smallint] NOT NULL
)


