IF TYPE_ID(N'SODTLCOMMODITY') IS NOT NULL
DROP TYPE SODTLCOMMODITY
GO

CREATE TYPE [dbo].[SODTLCOMMODITY] AS TABLE(
	[LNITMSEQ] [int] NOT NULL,
	[CMS_COMMODITY_DESC] [char](251) NOT NULL,
	[UOFM] [char](9) NOT NULL,
	[UMDPQTYS] [smallint] NOT NULL,
	[QTYSHPPD] [numeric](19, 5) NOT NULL,
	[CMS_WEIGHT] [numeric](19, 5) NOT NULL
)


