IF TYPE_ID(N'SODTLCHARGES') IS NOT NULL
DROP TYPE SODTLCHARGES
GO

CREATE TYPE [dbo].[SODTLCHARGES] AS TABLE (
	[CMS_QUOTATION_NO] [char](31) NOT NULL,
	[LNITMSEQ] [int] NOT NULL,
	[ITEMNMBR] [char](31) NOT NULL,
	[ITEMDESC] [char](101) NOT NULL,
	[QUANTITY] [numeric](19, 5) NOT NULL,
	[CHRGAMNT] [numeric](19, 5) NOT NULL,
	[TAXAMNT] [numeric](19, 5) NOT NULL,
	[SUBTOTAL] [numeric](19, 5) NOT NULL,
	[TOTAL] [numeric](19, 5) NOT NULL
)


