IF TYPE_ID(N'SODTLATTACHMENT') IS NOT NULL
DROP TYPE SODTLATTACHMENT
GO

CREATE TYPE [dbo].[SODTLATTACHMENT] AS TABLE (
	[DOCNUMBR] [char](21) NOT NULL,
	[DOCDATE] [datetime] NOT NULL,
	[CMS_SO_FILENAME] [char](501) NOT NULL,
	[CMS_SO_FILEPATH] [char](501) NOT NULL
)


