IF TYPE_ID(N'SODTLQUOTATION') IS NOT NULL
DROP TYPE SODTLQUOTATION
GO

CREATE TYPE [dbo].[SODTLQUOTATION] AS TABLE (
	[CMS_CONTRACT_NO] [char](21) NOT NULL,
	[CUSTNMBR] [char](15) NOT NULL,
	[CMS_QUOTATION_NO] [char](31) NOT NULL,
	[CMS_QUOTATION_TYPE] [smallint] NOT NULL,
	[DOCDATE] [datetime] NOT NULL,
	[CMS_DESC] [char](251) NOT NULL,
	[From_Date] [datetime] NOT NULL,
	[TODATE] [datetime] NOT NULL,
	[CURNCYID] [char](15) NOT NULL,
	[CMS_DPP] [numeric](19, 5) NOT NULL,
	[CMS_SELECTED] [smallint] NOT NULL
)

