IF TYPE_ID(N'SODTLROUTE') IS NOT NULL
DROP TYPE SODTLROUTE
GO

CREATE TYPE [dbo].[SODTLROUTE] AS TABLE (
	[CMS_QUOTATION_NO] [char](31) NOT NULL,
	[LNITMSEQ] [int] NOT NULL,
	[LNSEQNBR] [numeric](19, 5) NOT NULL,
	[CMS_ROUTEID_FROM] [char](21) NOT NULL,
	[CMS_ROUTEID_TO] [char](21) NOT NULL,
	[CMS_CONT_UKURAN_ID] [char](25) NOT NULL,
	[CMS_CONT_UKURAN] [char](51) NOT NULL,
	[CMS_KETERANGAN] [char](501) NOT NULL,
	[CMS_FLAGGING] [smallint] NOT NULL,
	[CMS_STUFF_LOCATION] [char](101) NOT NULL,
	[QUANTITY] [numeric](19, 5) NOT NULL,
	[UNITPRCE] [numeric](19, 5) NOT NULL,
	[XTNDPRCE] [numeric](19, 5) NOT NULL,
	[SUBTOTAL] [numeric](19, 5) NOT NULL,
	[TAXDTLID] [char](15) NOT NULL,
	[TXDTLPCT] [numeric](19, 5) NOT NULL,
	[TAXAMNT] [numeric](19, 5) NOT NULL,
	[TOTAL] [numeric](19, 5) NOT NULL,
	[CMS_SELECTED] [smallint] NOT NULL
)

