CREATE OR ALTER proc [dbo].[CMS_Contract_GetDataList]
(
 @USERID varchar(30)
)  
AS
BEGIN
	select distinct CMS_CONTRACT_NO, CMS_CONTRACT_TYPE, 
	CASE 
	WHEN CMS_CONTRACT_TYPE=1 THEN 'New'
	WHEN CMS_CONTRACT_TYPE=2 THEN 'Addendum'
	ELSE '' END CONTRACT_TYPE_TXT,
	DOCDATE, CMS_SUBMITTED_DATE, From_Date, TODATE, CMS_DURATION, CURNCYID, CRNCYSYM, CUSTNMBR, CUSTNAME, 
	PYMTTYPE, PYMTRMID, PYMNTTRM, TAXTYPE, TAXSCHID, TAXDTLID, TXDTLPCT, CMS_ORDER_TYPE, CMS_KETERANGAN, CMS_Status, CRUSRID, CREATDDT, CREATETIME, MDFUSRID, MODIFDT, MODIFTIME
	from CMS01131001C3
	WHERE CRUSRID=@USERID or MDFUSRID=@USERID
	ORDER BY MODIFDT, MODIFTIME desc
END
/*
exec [CMS_Contract_GetDataList] ''
*/
GO
