CREATE OR ALTER proc [dbo].[CMS_Contract_GetDetail]
(
 @CMS_CONTRACT_NO varchar(30),
 @TABLE varchar(30)
)  
AS
BEGIN
	IF @TABLE = 'header'
	BEGIN
		select distinct CMS_CONTRACT_NO, CMS_CONTRACT_TYPE, DOCDATE, CMS_SUBMITTED_DATE, From_Date, TODATE, CMS_DURATION, CURNCYID, CRNCYSYM, CUSTNMBR, CUSTNAME, 
		PYMTTYPE, PYMTRMID, PYMNTTRM, TAXTYPE, TAXSCHID, TAXDTLID, TXDTLPCT, CMS_ORDER_TYPE, CMS_KETERANGAN, CMS_Status, CRUSRID, CREATDDT, CREATETIME, MDFUSRID, MODIFDT, MODIFTIME
		from CMS01131001C3
		WHERE CMS_CONTRACT_NO=@CMS_CONTRACT_NO
		ORDER BY MODIFDT, MODIFTIME desc
	END
	ELSE IF @TABLE = 'route'
	BEGIN
		select distinct HDR.CMS_CONTRACT_NO, HDR.LNITMSEQ, HDR.LNSEQNBR, HDR.CMS_ROUTEID_FROM, COALESCE(ROU.DSCRIPTN, '') ROUTE_FROM, HDR.CMS_ROUTEID_TO, COALESCE(ROU2.DSCRIPTN, '') ROUTE_TO, 
		HDR.CMS_CONT_UKURAN_ID, HDR.CMS_CONT_UKURAN, HDR.CMS_KETERANGAN, HDR.CMS_STUFF_LOCATION, HDR.QUANTITY, HDR.UNITPRCE, HDR.XTNDPRCE, HDR.SUBTOTAL, HDR.TAXDTLID, HDR.TXDTLPCT, HDR.TAXAMNT, HDR.TOTAL
		from CMS01131002C3 HDR
		LEFT JOIN CMS01036002C3 ROU ON HDR.CMS_ROUTEID_FROM=ROU.CMS_Route_ID
		LEFT JOIN CMS01036002C3 ROU2 ON HDR.CMS_ROUTEID_TO=ROU2.CMS_Route_ID
		WHERE CMS_CONTRACT_NO=@CMS_CONTRACT_NO
		ORDER BY LNITMSEQ, LNSEQNBR
	END
	ELSE IF @TABLE = 'charges'
	BEGIN
		select distinct CMS_CONTRACT_NO, LNITMSEQ, ITEMNMBR, ITEMDESC, QUANTITY, CHRGAMNT, TAXAMNT, SUBTOTAL, TOTAL
		from CMS01131003C3
		WHERE CMS_CONTRACT_NO=@CMS_CONTRACT_NO
		ORDER BY LNITMSEQ
	END
END
/*
exec [CMS_Contract_GetDetail] 'CONTRACT/ID/00002', 'route'
*/
GO
