CREATE OR ALTER PROC [dbo].[CMS_SO_GET_LU_SALESORDER]
(
	@USERID VARCHAR(50),
	@INTERID VARCHAR(50)
)
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
			select CMS_SO_NO SALESORDERNO, CMS_DESC SALESORDERDESC
			from CMS01133001C3 with(nolock) --CMS_SO_HEADER
			order by CMS_SO_NO asc
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000), @ErrorSeverity INT, @ErrorState INT
		SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = ERROR_STATE()
		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState)
	END CATCH
END
GO

/*
	exec CMS_SO_GET_LU_SALESORDER '',''
	
	select * from CMS01133001C3 --CMS_SO_HEADER
*/


