CREATE OR ALTER proc CMS_Quotation_Save
(  
 @CMS_QUOTATION_NO varchar(21),
 @CMS_QUOTATION_TYPE varchar(30),
 @CMS_CONTRACT_NO varchar(21),
 @CMS_CONTRACT_TYPE int,
 @DOCDATE datetime,
 @CMS_SUBMITTED_DATE datetime,
 @From_Date datetime,
 @TODATE datetime,
 @LOCNCODE varchar(30), 
 @LOCNDSCR varchar(30),
 @CURNCYID varchar(15),
 @CRNCYSYM varchar(3),
 @CUSTNMBR varchar(15),
 @CUSTNAME varchar(65),
 @ADRSCODE varchar(15),
 @PYMTTYPE int,
 @PYMTRMID varchar(21),
 @PYMNTTRM varchar(15),
 @TAXTYPE int,
 @TAXSCHID varchar(15),
 @TAXDTLID varchar(15),
 @TXDTLPCT int,
 @CMS_ORDER_TYPE int,
 @CMS_KETERANGAN varchar(501),
 @CMS_Status int,
 @USERID varchar(30),
 @QUOROUTE QUOROUTE readonly,
 @QUOCHRGS QUOCHRGS readonly
)  
AS BEGIN  
	BEGIN TRY
		--begin transaction
		--header
		IF EXISTS(select top 1 * from CMS01131004C3 WHERE CMS_QUOTATION_NO=@CMS_QUOTATION_NO)
		BEGIN
			UPDATE CMS01131004C3 SET CMS_QUOTATION_TYPE=@CMS_QUOTATION_TYPE, CMS_CONTRACT_NO=@CMS_CONTRACT_NO, CMS_CONTRACT_TYPE=@CMS_CONTRACT_TYPE, DOCDATE=@DOCDATE, 
			CMS_SUBMITTED_DATE=@CMS_SUBMITTED_DATE, From_Date=@From_Date, TODATE=@TODATE, LOCNCODE=@LOCNCODE, LOCNDSCR=@LOCNDSCR, CURNCYID=@CURNCYID, CRNCYSYM=@CRNCYSYM, 
			CUSTNMBR=@CUSTNMBR, CUSTNAME=@CUSTNAME, ADRSCODE=@ADRSCODE, PYMTTYPE=@PYMTTYPE, PYMTRMID=@PYMTRMID, PYMNTTRM=@PYMNTTRM, TAXTYPE=@TAXTYPE, TAXSCHID=@TAXSCHID, 
			TAXDTLID=@TAXDTLID, TXDTLPCT=@TXDTLPCT, CMS_ORDER_TYPE=@CMS_ORDER_TYPE, CMS_KETERANGAN=@CMS_KETERANGAN, CMS_Status=@CMS_Status, 
			MDFUSRID=@USERID, MODIFDT=CAST(GETDATE() as date), MODIFTIME=CAST(GETDATE() as time)
			WHERE CMS_QUOTATION_NO=@CMS_QUOTATION_NO
		END
		ELSE 
		BEGIN
			insert into CMS01131004C3(CMS_QUOTATION_NO, CMS_QUOTATION_TYPE, CMS_CONTRACT_NO, CMS_CONTRACT_TYPE, DOCDATE, CMS_SUBMITTED_DATE, From_Date, TODATE, LOCNCODE, LOCNDSCR, CURNCYID, CRNCYSYM, CUSTNMBR, CUSTNAME, 
			ADRSCODE, PYMTTYPE, PYMTRMID, PYMNTTRM, TAXTYPE, TAXSCHID, TAXDTLID, TXDTLPCT, CMS_ORDER_TYPE, CMS_KETERANGAN, CMS_Status, CRUSRID, CREATDDT, CREATETIME, MDFUSRID, MODIFDT, MODIFTIME)
			values
			(@CMS_QUOTATION_NO, @CMS_QUOTATION_TYPE, @CMS_CONTRACT_NO, @CMS_CONTRACT_TYPE, @DOCDATE, @CMS_SUBMITTED_DATE, @From_Date, @TODATE, @LOCNCODE, @LOCNDSCR, @CURNCYID, @CRNCYSYM, @CUSTNMBR, @CUSTNAME, 
			@ADRSCODE, @PYMTTYPE, @PYMTRMID, @PYMNTTRM, @TAXTYPE, @TAXSCHID, @TAXDTLID, @TXDTLPCT, @CMS_ORDER_TYPE, @CMS_KETERANGAN, @CMS_Status, @USERID, CAST(GETDATE() as date), CAST(GETDATE() as time),
			@USERID, CAST(GETDATE() as date), CAST(GETDATE() as time))
		END
		
		--detail route
		delete from CMS01131005C3 where RTRIM(CMS_QUOTATION_NO)=RTRIM(@CMS_QUOTATION_NO)

		insert into CMS01131005C3(CMS_QUOTATION_NO, LNITMSEQ, LNSEQNBR, CMS_ROUTEID_FROM, CMS_ROUTEID_TO, CMS_CONT_UKURAN_ID, CMS_CONT_UKURAN, CMS_KETERANGAN, 
		CMS_STUFF_LOCATION, QUANTITY, UNITPRCE, XTNDPRCE, SUBTOTAL, TAXDTLID, TXDTLPCT, TAXAMNT, TOTAL)
		select distinct CMS_QUOTATION_NO, LNITMSEQ, LNSEQNBR, CMS_ROUTEID_FROM, CMS_ROUTEID_TO, CMS_CONT_UKURAN_ID, CMS_CONT_UKURAN, CMS_KETERANGAN, 
		CMS_STUFF_LOCATION, QUANTITY, UNITPRCE, XTNDPRCE, SUBTOTAL, TAXDTLID, TXDTLPCT, TAXAMNT, TOTAL
		from @QUOROUTE
		
		--detail charges
		delete from CMS01131006C3 where RTRIM(CMS_QUOTATION_NO)=RTRIM(@CMS_QUOTATION_NO)

		insert into CMS01131006C3(CMS_QUOTATION_NO, LNITMSEQ, ITEMNMBR, ITEMDESC, QUANTITY, CHRGAMNT, TAXAMNT, SUBTOTAL, TOTAL)
		select distinct CMS_QUOTATION_NO, LNITMSEQ, ITEMNMBR, ITEMDESC, QUANTITY, CHRGAMNT, TAXAMNT, SUBTOTAL, TOTAL 
		from @QUOCHRGS
	--commit
	END TRY
	BEGIN CATCH
		--rollback
		DECLARE @ErrorMessage NVARCHAR(4000)
		DECLARE @ErrorSeverity INT
		DECLARE @ErrorState INT

		SELECT @ErrorMessage = ERROR_MESSAGE(),
			   @ErrorSeverity = ERROR_SEVERITY(),
			   @ErrorState = ERROR_STATE()

		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState)
		select @ErrorMessage as output
	END CATCH 
END  
/*  

declare @p27 dbo.QUOROUTE
insert into @p27 values(N'QUOTATION/00001',16384,0,N'JKT',N'RUTE2',N'20Dry',N'20Dry',N'test1',N'tester stuff 1',50,10000000,500000000,50,N'600000000',0,0,600000000)
insert into @p27 values(N'QUOTATION/00001',16384,16384,N'JKT',N'RUTE2',N'20Dry',N'20Dry',N'test1.1',N'tester stuff 1.1',50,10000000,500000000,50,N'600000000',0,0,600000000)
insert into @p27 values(N'QUOTATION/00001',32768,0,N'AMBON',N'RUTE3',N'40RF',N'40RF',N'test2',N'tester stuff 2',20,5000000,100000000,20,N'600000000',0,0,600000000)
insert into @p27 values(N'QUOTATION/00001',32768,16384,N'AMBON',N'RUTE3',N'40RF',N'40RF',N'test2.1',N'tester stuff 2.1',20,5000000,100000000,20,N'600000000',0,0,600000000)

declare @p28 dbo.QUOCHRGS
insert into @p28 values(N'QUOTATION/00001',16384,N'AGENT-BURU',N'tester',10,25000000,250000,25250000,25250000)

exec CMS_Quotation_Save @CMS_QUOTATION_NO=N'QUOTATION/00001',@CMS_QUOTATION_TYPE=N'test',@CMS_CONTRACT_NO=N'CONTRACT/ID/00002',@CMS_CONTRACT_TYPE=0,@DOCDATE='2023-05-27 00:00:00',
@CMS_SUBMITTED_DATE='2023-05-27 00:00:00',@From_Date='2023-06-01 00:00:00',@TODATE='2023-06-30 00:00:00',@LOCNCODE=N'110113',@LOCNDSCR=N'Narogong Pool - P4',@CURNCYID=N'IDR',@CRNCYSYM=N'Rp',
@CUSTNMBR=N'AAR',@CUSTNAME=N'ALI ARRIDHO',@ADRSCODE=N'ALI ARRIDHO',@PYMTTYPE=2,@PYMTRMID=N'14 Days',@PYMNTTRM=N'14 Days',@TAXTYPE=0,@TAXSCHID=N'VAT OUT 1%',@TAXDTLID=N'VAT OUT 1%',@TXDTLPCT=1,
@CMS_ORDER_TYPE=1,@CMS_KETERANGAN=N'tester',@CMS_Status=1,@USERID=N'teg01          ',@QUOROUTE=@p27,@QUOCHRGS=@p28

*/
GO