CREATE OR ALTER proc [dbo].[CMS_Planned_GetChargesBySO]
(
 @CMS_SO_NO varchar(30),
 @CMS_QUOTATION_NO varchar(30)
)  
AS
BEGIN 
	select distinct CMS_SO_NO, CMS_QUOTATION_NO, LNITMSEQ, ITEMNMBR, ITEMDESC, QUANTITY, CHRGAMNT, TAXAMNT, SUBTOTAL, TOTAL 
	from CMS01133005C3
	WHERE CMS_SO_NO=@CMS_SO_NO and CMS_QUOTATION_NO=@CMS_QUOTATION_NO
	order by LNITMSEQ
END
/*
exec [CMS_Planned_GetChargesBySO] 'SO/2305/0001', 'QUOTATION/00001'
*/
GO
