CREATE OR ALTER proc CMS_Contract_GetStatus
(
 @USERID varchar(30)
)
AS BEGIN  
	SELECT DISTINCT CMS_Status
	FROM CMS01131001C3
	WHERE CRUSRID=@USERID or MDFUSRID=@USERID
	ORDER BY CMS_Status
END  
/*  
  
exec CMS_Contract_GetStatus 'E_MKA'
  
*/
GO