CREATE OR ALTER proc [dbo].[CMS_Get_Tax]
AS
BEGIN
	select distinct TXSC.TAXSCHID, COALESCE(TXID.TAXDTLID, '') TAXDTLID, COALESCE(TXID.TXDTLDSC, '') TXDTLDSC, 
	COALESCE(TXID.TXDTLPCT, 0) TXDTLPCT, COALESCE(TXID.TXDTLAMT, 0) TXDTLAMT
	from TX00102 TXSC
	LEFT JOIN TX00201 TXID ON TXSC.TAXDTLID=TXID.TAXDTLID
END
/*
exec [CMS_Get_Tax]
*/
GO
