CREATE OR ALTER proc [dbo].[CMS_Quotation_GetDataList]
(
 @USERID varchar(30)
)  
AS
BEGIN
	select distinct CMS_QUOTATION_NO, CMS_QUOTATION_TYPE, CMS_CONTRACT_NO, CMS_CONTRACT_TYPE, DOCDATE, CMS_SUBMITTED_DATE, From_Date, TODATE, LOCNCODE, LOCNDSCR, CURNCYID, CRNCYSYM, CUSTNMBR, CUSTNAME, 
	ADRSCODE, PYMTTYPE, PYMTRMID, PYMNTTRM, TAXTYPE, TAXSCHID, TAXDTLID, TXDTLPCT, CMS_ORDER_TYPE, CMS_KETERANGAN, CMS_Status, CRUSRID, CREATDDT, CREATETIME, MDFUSRID, MODIFDT, MODIFTIME
	from CMS01131004C3
	WHERE CRUSRID=@USERID or MDFUSRID=@USERID
	ORDER BY MODIFDT, MODIFTIME desc
END
/*
exec [CMS_Quotation_GetDataList] ''
*/
GO
