CREATE OR ALTER PROC [dbo].[CMS_SO_GET_LU_UOFM]
(
	@USERID VARCHAR(50),
	@INTERID VARCHAR(50),
	@PREFIX VARCHAR(250) = ''
)
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
			select RTRIM(UOMSCHDL) UOMSCHDL, RTRIM(UMSCHDSC) UMSCHDSC, RTRIM(BASEUOFM) BASEUOFM, COALESCE(UMDPQTYS,0) UMDPQTYS
			from IV40201 with(nolock) --UOM Header
			where UOMSCHDL like '%' + @PREFIX + '%'
			order by UOMSCHDL asc
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000), @ErrorSeverity INT, @ErrorState INT
		SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = ERROR_STATE()
		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState)
	END CATCH
END
GO

/*
	exec CMS_SO_GET_LU_UOFM '','','M'
	
	select * from IV40201 --UOM Header

	UOMSCHDL	UMSCHDSC	BASEUOFM	UMDPQTYS
*/


