CREATE OR ALTER proc [dbo].[CMS_Quotation_GetDetail]
(
 @CMS_QUOTATION_NO varchar(30),
 @TABLE varchar(30)
)  
AS
BEGIN
	IF @TABLE = 'header'
	BEGIN
		select distinct HDR.CMS_QUOTATION_NO, HDR.CMS_QUOTATION_TYPE, HDR.CMS_CONTRACT_NO, HDR.CMS_CONTRACT_TYPE, HDR.DOCDATE, HDR.CMS_SUBMITTED_DATE, HDR.From_Date, HDR.TODATE, HDR.LOCNCODE, HDR.LOCNDSCR, 
		HDR.CURNCYID, HDR.CRNCYSYM, HDR.CUSTNMBR, HDR.CUSTNAME, HDR.ADRSCODE, COALESCE(ADR.ADDRESS1, '') ADDRESS1, COALESCE(ADDRESS2, '') ADDRESS2, COALESCE(ADDRESS3, '') ADDRESS3, 
		COALESCE(COUNTRY, '') COUNTRY, COALESCE(CITY, '') CITY, COALESCE(STATE, '') STATE, COALESCE(ZIP, '') ZIP, HDR.PYMTTYPE, HDR.PYMTRMID, HDR.PYMNTTRM, HDR.TAXTYPE, 
		HDR.TAXSCHID, HDR.TAXDTLID, HDR.TXDTLPCT, HDR.CMS_ORDER_TYPE, HDR.CMS_KETERANGAN, HDR.CMS_Status, HDR.CRUSRID, HDR.CREATDDT, HDR.CREATETIME, HDR.MDFUSRID, HDR.MODIFDT, HDR.MODIFTIME
		from CMS01131004C3 HDR
		LEFT JOIN RM00102 ADR ON HDR.ADRSCODE=ADR.ADRSCODE
		WHERE CMS_QUOTATION_NO=@CMS_QUOTATION_NO
		ORDER BY MODIFDT, MODIFTIME desc
	END
	ELSE IF @TABLE = 'route'
	BEGIN
		select distinct HDR.CMS_QUOTATION_NO, HDR.LNITMSEQ, HDR.LNSEQNBR, HDR.CMS_ROUTEID_FROM, COALESCE(ROU.DSCRIPTN, '') ROUTE_FROM, HDR.CMS_ROUTEID_TO, COALESCE(ROU2.DSCRIPTN, '') ROUTE_TO, 
		HDR.CMS_CONT_UKURAN_ID, HDR.CMS_CONT_UKURAN, HDR.CMS_KETERANGAN, HDR.CMS_STUFF_LOCATION, HDR.QUANTITY, HDR.UNITPRCE, HDR.XTNDPRCE, HDR.SUBTOTAL, HDR.TAXDTLID, HDR.TXDTLPCT, HDR.TAXAMNT, HDR.TOTAL
		from CMS01131005C3 HDR
		LEFT JOIN CMS01036002C3 ROU ON HDR.CMS_ROUTEID_FROM=ROU.CMS_Route_ID
		LEFT JOIN CMS01036002C3 ROU2 ON HDR.CMS_ROUTEID_TO=ROU2.CMS_Route_ID
		WHERE CMS_QUOTATION_NO=@CMS_QUOTATION_NO
		ORDER BY LNITMSEQ, LNSEQNBR
	END
	ELSE IF @TABLE = 'charges'
	BEGIN
		select distinct CMS_QUOTATION_NO, LNITMSEQ, ITEMNMBR, ITEMDESC, QUANTITY, CHRGAMNT, TAXAMNT, SUBTOTAL, TOTAL
		from CMS01131006C3
		WHERE CMS_QUOTATION_NO=@CMS_QUOTATION_NO
		ORDER BY LNITMSEQ
	END
END
/*
exec [CMS_Quotation_GetDetail] 'CONTRACT/ID/00002', 'route'
*/
GO
