CREATE OR ALTER PROC [dbo].[CMS_SO_GET_DTL_QUOTATION_BY_CUSTOMER]
(
	@USERID VARCHAR(50),
	@INTERID VARCHAR(50),
	@PREFIX VARCHAR(50) = ''
)
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		select A.CMS_QUOTATION_NO, A.CMS_QUOTATION_TYPE, A.CMS_CONTRACT_NO, A.CMS_KETERANGAN, A.DOCDATE, A.From_Date, A.TODATE, A.CURNCYID, A.CRNCYSYM, C.SUBTOTAL DPP
		, 0 CHECKED, 'QUOTATION' DATATYPE, A.CUSTNMBR
		from CMS01131004C3 A --CMS_QUOTATION_HEADER
		left join (
			select CMS_QUOTATION_NO, SUM(SUBTOTAL) SUBTOTAL from CMS01131005C3 --CMS_QUOTATION_DTLROUTE
			group by CMS_QUOTATION_NO
		) C on C.CMS_QUOTATION_NO = A.CMS_QUOTATION_NO
		where A.CUSTNMBR = @PREFIX

		select A.CMS_CONTRACT_NO, B.CMS_QUOTATION_NO, B.CMS_KETERANGAN, B.LNITMSEQ, B.LNSEQNBR, B.CMS_ROUTEID_TO, B.CMS_ROUTEID_FROM, B.CMS_CONT_UKURAN_ID, B.CMS_CONT_UKURAN
		, B.CMS_STUFF_LOCATION, B.QUANTITY, B.UNITPRCE, B.XTNDPRCE, B.SUBTOTAL, B.TAXAMNT, B.TOTAL, 0 FLAGGING
		, 0 CHECKED, 'ROUTE' DATATYPE
		from CMS01131004C3 A --CMS_QUOTATION_HEADER
		left join CMS01131005C3 B ON B.CMS_QUOTATION_NO = A.CMS_QUOTATION_NO --CMS_QUOTATION_DTLROUTE
		where A.CUSTNMBR = @PREFIX
		
		select A.CMS_CONTRACT_NO, B.CMS_QUOTATION_NO, B.LNITMSEQ, B.ITEMNMBR, B.ITEMDESC, B.QUANTITY, B.CHRGAMNT, B.TAXAMNT, B.SUBTOTAL, B.TOTAL
		, 'CHARGES' DATATYPE
		from CMS01131004C3 A --CMS_QUOTATION_HEADER
		left join CMS01131006C3 B on B.CMS_QUOTATION_NO = A.CMS_QUOTATION_NO --CMS_QUOTATION_DTLCHARGES
		where A.CUSTNMBR = @PREFIX
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000), @ErrorSeverity INT, @ErrorState INT
		SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = ERROR_STATE()
		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState)
	END CATCH
END
GO

/*
	exec CMS_SO_GET_DTL_QUOTATION_BY_CUSTOMER '','','AAM'

	select * from CMS01131004C3 --CMS_QUOTATION_HEADER
	select * from CMS01131005C3 --CMS_QUOTATION_DTLROUTE
	select * from CMS01131006C3 --CMS_QUOTATION_DTLCHARGES

*/




