CREATE OR ALTER proc [dbo].[CMS_Lookup_RouteBySO]
(
 @CMS_SO_NO varchar(30),
 @CMS_QUOTATION_NO varchar(30)
)  
AS
BEGIN 
	select distinct HDR.CMS_SO_NO, HDR.CMS_QUOTATION_NO, HDR.LNITMSEQ, HDR.LNSEQNBR, HDR.CMS_ROUTEID_FROM, COALESCE(ROU.DSCRIPTN, '') ROUTE_FROM, 
	HDR.CMS_ROUTEID_TO, COALESCE(ROU2.DSCRIPTN, '') ROUTE_TO, HDR.CMS_CONT_UKURAN_ID, HDR.CMS_CONT_UKURAN, HDR.CMS_KETERANGAN, HDR.CMS_FLAGGING, 
	HDR.CMS_STUFF_LOCATION, HDR.QUANTITY, HDR.UNITPRCE, HDR.XTNDPRCE, HDR.SUBTOTAL, HDR.TAXDTLID, HDR.TXDTLPCT, HDR.TAXAMNT, HDR.TOTAL, HDR.CMS_SELECTED
	from CMS01133004C3 HDR
	LEFT JOIN CMS01036002C3 ROU ON HDR.CMS_ROUTEID_FROM=ROU.CMS_Route_ID
	LEFT JOIN CMS01036002C3 ROU2 ON HDR.CMS_ROUTEID_TO=ROU2.CMS_Route_ID
	WHERE HDR.CMS_SELECTED=1 and CAST(ISNULL(HDR.LNSEQNBR, 0) as INT)=0
	and HDR.CMS_SO_NO=@CMS_SO_NO and HDR.CMS_QUOTATION_NO=@CMS_QUOTATION_NO
	order by HDR.LNITMSEQ
END
/*
exec [CMS_Lookup_RouteBySO] '', ''
*/
GO
