CREATE OR ALTER proc [dbo].[CMS_Lookup_DefaultCurrency]
AS
BEGIN
	select distinct A.FUNLCURR, COALESCE(B.CRNCYDSC, '') CRNCYDSC, COALESCE(B.CRNCYSYM, '') CRNCYSYM 
	from MC40000 A
	LEFT JOIN DYNAMICS..MC40200 B ON A.FUNLCURR=B.CURNCYID
END
/*
exec [CMS_Lookup_DefaultCurrency]
*/
GO
