CREATE OR ALTER PROC [dbo].[CMS_SO_PROCESS]
(
	@USERID varchar(30),
	@INTERID varchar(30),
	@CMS_SO_NO varchar(31),
	@CMS_SUBMITTED_DATE datetime,
	@CMS_CONTRACT_NO varchar(21),
	@CMS_SALES_TYPE int,
	@CMS_ORDER_TYPE int,
	@DOCDATE datetime,
	@LOCNCODE varchar(11),
	@LOCNDSCR varchar(31),
	@CURNCYID varchar(15),
	@CRNCYDSC varchar(31),
	@CUSTNMBR varchar(15),
	@CUSTNAME varchar(65),
	@PYMTTYPE int,
	@PYMTRMID varchar(21),
	@CMS_CUSTNMBR_BTA varchar(31),
	@CMS_STUFFING_DATE datetime,
	@CMS_CONT_TYPE int,
	@CMS_CONT_NO varchar(25),
	@CMS_DESC varchar(251),
	@CMS_Status int,
	@SODTLATTACHMENT SODTLATTACHMENT readonly,
	@SODTLQUOTATION SODTLQUOTATION readonly,
	@SODTLROUTE SODTLROUTE readonly,
	@SODTLCHARGES SODTLCHARGES readonly,
	@SODTLCOMMODITY SODTLCOMMODITY readonly,
	@SODTLDOCCHECKLIST SODTLDOCCHECKLIST readonly
)
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		if LEN(RTRIM(@CMS_SO_NO)) <= 0
		begin
			select @CMS_SO_NO = 'SO' + format(getdate(), '-MMyy-') + right(cast(cast(coalesce(max(right(RTRIM(CMS_SO_NO),5)),0) as int) + 100001 as varchar(6)),5)
			from CMS01133001C3 with(nolock)
			where CMS_SO_NO like 'SO' + format(getdate(), '-MMyy-') + '%'
		end
		
		--insert so hdr
		if not exists (select top 1 * from CMS01133001C3 with(nolock) where CMS_SO_NO = @CMS_SO_NO)
		begin
			insert into CMS01133001C3
			(CMS_SO_NO, CMS_SUBMITTED_DATE, CMS_CONTRACT_NO, CMS_SALES_TYPE, CMS_ORDER_TYPE, DOCDATE, LOCNCODE, LOCNDSCR
			, CURNCYID, CRNCYDSC, CUSTNMBR, CUSTNAME, PYMTTYPE, PYMTRMID, CMS_CUSTNMBR_BTA, CMS_STUFFING_DATE, CMS_CONT_TYPE
			, CMS_CONT_NO, CMS_DESC, CMS_Status
			, CRUSRID, CREATDDT, CREATETIME, MDFUSRID, MODIFDT, MODIFTIME)
			select @CMS_SO_NO, cast(@CMS_SUBMITTED_DATE as date), @CMS_CONTRACT_NO, @CMS_SALES_TYPE, @CMS_ORDER_TYPE, cast(@DOCDATE as date), @LOCNCODE, @LOCNDSCR
			, @CURNCYID, @CRNCYDSC, @CUSTNMBR, @CUSTNAME, @PYMTTYPE, @PYMTRMID, @CMS_CUSTNMBR_BTA, cast(@CMS_STUFFING_DATE as date)
			, @CMS_CONT_TYPE, @CMS_CONT_NO, @CMS_DESC, @CMS_Status
			, @USERID, cast(getdate() as date), cast(getdate() as time), @USERID, cast(getdate() as date), cast(getdate() as time)
		end else begin
			update CMS01133001C3
			set CMS_SUBMITTED_DATE = cast(@CMS_SUBMITTED_DATE as date), CMS_CONTRACT_NO = @CMS_CONTRACT_NO, CMS_SALES_TYPE = @CMS_SALES_TYPE
			, CMS_ORDER_TYPE=@CMS_ORDER_TYPE, DOCDATE=cast(@DOCDATE as date), LOCNCODE=@LOCNCODE, LOCNDSCR=@LOCNDSCR, CURNCYID=@CURNCYID
			, CRNCYDSC=@CRNCYDSC, CUSTNMBR=@CUSTNMBR, CUSTNAME=@CUSTNAME, PYMTTYPE=@PYMTTYPE, PYMTRMID=@PYMTRMID, CMS_CUSTNMBR_BTA=@CMS_CUSTNMBR_BTA
			, CMS_STUFFING_DATE=cast(@CMS_STUFFING_DATE as date), CMS_CONT_TYPE=@CMS_CONT_TYPE, CMS_CONT_NO=@CMS_CONT_NO, CMS_DESC=@CMS_DESC
			, CMS_Status=@CMS_Status
			, CRUSRID=@USERID, CREATDDT=cast(getdate() as date), CREATETIME=cast(getdate() as time), MDFUSRID=@USERID, MODIFDT=cast(getdate() as date), MODIFTIME=cast(getdate() as time)
			where CMS_SO_NO = @CMS_SO_NO
		end

		--delete insert so detail attachment
		delete from CMS01133002C3 where CMS_SO_NO=@CMS_SO_NO
		insert into CMS01133002C3
		(CMS_SO_NO, DOCNUMBR, DOCDATE, CMS_SO_FILENAME, CMS_SO_FILEPATH)
		select @CMS_SO_NO, DOCNUMBR, cast(DOCDATE as date), CMS_SO_FILENAME, CMS_SO_FILEPATH
		from @SODTLATTACHMENT

		--delete insert so detail quotation
		delete from CMS01133003C3 where CMS_SO_NO=@CMS_SO_NO
		insert into CMS01133003C3
		(CMS_SO_NO, CMS_CONTRACT_NO, CUSTNMBR, CMS_QUOTATION_NO, CMS_QUOTATION_TYPE, DOCDATE, CMS_DESC, From_Date, TODATE
		, CURNCYID, CMS_DPP, CMS_SELECTED)
		select @CMS_SO_NO, CMS_CONTRACT_NO, CUSTNMBR, CMS_QUOTATION_NO, CMS_QUOTATION_TYPE, cast(DOCDATE as date), CMS_DESC, cast(From_Date as date), cast(TODATE as date)
		, CURNCYID, CMS_DPP, CMS_SELECTED
		from @SODTLQUOTATION
		
		--delete insert so detail route
		delete from CMS01133004C3 where CMS_SO_NO=@CMS_SO_NO
		insert into CMS01133004C3
		(CMS_SO_NO, CMS_QUOTATION_NO, LNITMSEQ, LNSEQNBR, CMS_ROUTEID_FROM, CMS_ROUTEID_TO, CMS_CONT_UKURAN_ID, CMS_CONT_UKURAN, CMS_KETERANGAN, CMS_FLAGGING
		, CMS_STUFF_LOCATION, QUANTITY, UNITPRCE, XTNDPRCE, SUBTOTAL, TAXDTLID, TXDTLPCT, TAXAMNT, TOTAL, CMS_SELECTED)
		select @CMS_SO_NO, CMS_QUOTATION_NO, LNITMSEQ, LNSEQNBR, CMS_ROUTEID_FROM, CMS_ROUTEID_TO, CMS_CONT_UKURAN_ID, CMS_CONT_UKURAN, CMS_KETERANGAN, CMS_FLAGGING
		, CMS_STUFF_LOCATION, QUANTITY, UNITPRCE, XTNDPRCE, SUBTOTAL, TAXDTLID, TXDTLPCT, TAXAMNT, TOTAL, CMS_SELECTED
		from @SODTLROUTE

		--delete insert so detail charges
		delete from CMS01133005C3 where CMS_SO_NO=@CMS_SO_NO
		insert into CMS01133005C3
		(CMS_SO_NO, CMS_QUOTATION_NO, LNITMSEQ, ITEMNMBR, ITEMDESC, QUANTITY, CHRGAMNT, TAXAMNT, SUBTOTAL, TOTAL)
		select @CMS_SO_NO, CMS_QUOTATION_NO, LNITMSEQ, ITEMNMBR, ITEMDESC, QUANTITY, CHRGAMNT, TAXAMNT, SUBTOTAL, TOTAL
		from @SODTLCHARGES

		--delete insert so detail commodity
		delete from CMS01133006C3 where CMS_SO_NO=@CMS_SO_NO
		insert into CMS01133006C3
		(CMS_SO_NO, LNITMSEQ, CMS_COMMODITY_DESC, UOFM, UMDPQTYS, QTYSHPPD, CMS_WEIGHT)
		select @CMS_SO_NO, LNITMSEQ, CMS_COMMODITY_DESC, UOFM, UMDPQTYS, QTYSHPPD, CMS_WEIGHT
		from @SODTLCOMMODITY

		--delete insert so detail document checklist
		delete from CMS01133007C3 where CMS_SO_NO=@CMS_SO_NO
		insert into CMS01133007C3
		(CMS_SO_NO, CUSTNMBR, DOCNUMBR, DSCRIPTN, QUANTITY, LNITMSEQ, CMS_SELECTED)
		select @CMS_SO_NO, CUSTNMBR, DOCNUMBR, DSCRIPTN, QUANTITY, LNITMSEQ, CMS_SELECTED
		from @SODTLDOCCHECKLIST

		select @CMS_SO_NO CMS_SO_NO

	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000), @ErrorSeverity INT, @ErrorState INT
		SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = ERROR_STATE()
		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState)
	END CATCH
END
GO

/*
	select * from CMS01133001C3 --CMS_SO_HEADER
	select * from CMS01133002C3 --CMS_SO_DTL_ATTACHMENT
	select * from CMS01133003C3 --CMS_SO_DTL_QUOTATION
	select * from CMS01133004C3 --CMS_SO_DTL_ROUTE
	select * from CMS01133005C3 --CMS_SO_DTL_CHARGES
	select * from CMS01133006C3 --CMS_SO_DTL_COMMODITY
	select * from CMS01133007C3 --CMS_SO_DTL_DOCCHECKLIST

*/


