CREATE OR ALTER proc [dbo].[CMS_Lookup_SOApproved]
AS
BEGIN
	SELECT distinct CMS_SO_NO, CMS_DESC, CMS_SUBMITTED_DATE FROM CMS01133001C3
	WHERE CMS_Status=3
	ORDER BY CMS_SUBMITTED_DATE
END
/*
exec [CMS_Lookup_SOApproved]
*/
GO
