CREATE OR ALTER proc [dbo].[CMS_Planned_GetDetailBySO]
(
 @CMS_SO_NO varchar(30),
 @CMS_QUOTATION_NO varchar(30),
 @LNITMSEQ INT
)  
AS
BEGIN 
	select distinct DTL.CMS_SO_NO, DTL.CMS_QUOTATION_NO, DTL.LNITMSEQ, DTL.LNSEQNBR, DTL.CMS_ROUTEID_FROM, COALESCE(ROU.DSCRIPTN, '') ROUTE_FROM, 
	DTL.CMS_ROUTEID_TO, COALESCE(ROU2.DSCRIPTN, '') ROUTE_TO, DTL.CMS_CONT_UKURAN_ID, DTL.CMS_CONT_UKURAN, DTL.CMS_KETERANGAN, 
	COALESCE(HDR.LOCNCODE, '') LOCNCODE, COALESCE(HDR.LOCNDSCR, '') LOCNDSCR,
	CASE
	WHEN DTL.CMS_FLAGGING=1 THEN 'SOC (Shipper Owned Container)'
	WHEN DTL.CMS_FLAGGING=2 THEN 'COC (Carrier Owned Container)'
	ELSE '' END CMS_FLAGGING_TXT, DTL.CMS_FLAGGING,
	DTL.CMS_STUFF_LOCATION, DTL.QUANTITY, DTL.UNITPRCE, DTL.XTNDPRCE, DTL.SUBTOTAL, DTL.TAXDTLID, DTL.TXDTLPCT, DTL.TAXAMNT, DTL.TOTAL, DTL.CMS_SELECTED
	from CMS01133004C3 DTL
	LEFT JOIN CMS01133001C3 HDR ON DTL.CMS_SO_NO=HDR.CMS_SO_NO
	LEFT JOIN CMS01036002C3 ROU ON DTL.CMS_ROUTEID_FROM=ROU.CMS_Route_ID
	LEFT JOIN CMS01036002C3 ROU2 ON DTL.CMS_ROUTEID_TO=ROU2.CMS_Route_ID
	WHERE DTL.CMS_SELECTED=1 
	and DTL.CMS_SO_NO=@CMS_SO_NO and DTL.CMS_QUOTATION_NO=@CMS_QUOTATION_NO and DTL.LNITMSEQ=@LNITMSEQ
	order by DTL.LNITMSEQ, DTL.LNSEQNBR
END
/*
exec [CMS_Planned_GetDetailBySO] 'SO/2305/0001', 'QUOTATION/00001', 16384
*/
GO
