CREATE OR ALTER proc [dbo].[CMS_Lookup_QuotationBySO]
(
@CMS_SO_NO VARCHAR(30)
)
AS
BEGIN
	SELECT distinct A.CMS_SO_NO, COALESCE(B.CMS_QUOTATION_NO, '') CMS_QUOTATION_NO, COALESCE(B.CMS_DESC, '') CMS_DESC 
	FROM CMS01133001C3 A
	LEFT JOIN CMS01133003C3 B ON A.CMS_SO_NO=B.CMS_SO_NO
	WHERE RTRIM(A.CMS_SO_NO)=RTRIM(@CMS_SO_NO)
	and A.CMS_Status=3 
	ORDER BY CMS_QUOTATION_NO
END
/*
exec [CMS_Lookup_QuotationBySO] ''
*/
GO
