CREATE OR ALTER proc [dbo].[CMS_Get_TaxByCust]
(
@CUSTNMBR varchar(30)
)
AS
BEGIN
	select distinct CST.CUSTNMBR, CST.CUSTNAME, CST.TAXSCHID,
	COALESCE(TXID.TAXDTLID, '') TAXDTLID, COALESCE(TXID.TXDTLDSC, '') TXDTLDSC, 
	COALESCE(TXID.TXDTLPCT, 0) TXDTLPCT, COALESCE(TXID.TXDTLAMT, 0) TXDTLAMT
	from RM00101 CST
	LEFT JOIN TX00102 TXSC ON CST.TAXSCHID=TXSC.TAXSCHID
	LEFT JOIN TX00201 TXID ON TXSC.TAXDTLID=TXID.TAXDTLID
	where CST.INACTIVE=0 and CST.CUSTNMBR=@CUSTNMBR
END
/*
exec [CMS_Get_TaxByCust] 'AAR'
*/
GO
