CREATE OR ALTER PROC [dbo].[CMS_SO_GET_DATA_SALESORDER]
(
	@USERID VARCHAR(50),
	@INTERID VARCHAR(50),
	@PREFIX VARCHAR(50) = ''
)
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		select A.CMS_SO_NO, A.CMS_SUBMITTED_DATE, A.CMS_CONTRACT_NO, A.CMS_SALES_TYPE, A.CMS_ORDER_TYPE, A.DOCDATE, A.LOCNCODE, A.LOCNDSCR, A.CURNCYID, A.CRNCYDSC
		, A.CUSTNMBR, A.CUSTNAME, A.PYMTTYPE, A.PYMTRMID, A.CMS_CUSTNMBR_BTA, A.CMS_STUFFING_DATE, A.CMS_CONT_TYPE, A.CMS_CONT_NO, A.CMS_DESC, A.CMS_Status, 'HDR' DATATYPE
		, B.CRNCYSYM, B.DECPLCUR
		, case B.DECSYMBL when 1 then 'space' when 2 then '.' when 3 then ',' when 4 then '$' end DECSYMBL
		, case B.THOUSSYM when 1 then	'space' when 2 then '.' when 3 then ',' when 4 then '''' end THOUSSYM
		from CMS01133001C3 A with(nolock) --CMS_SO_HEADER
		left join DYNAMICS..MC40200 B on B.CURNCYID=A.CURNCYID--Currency Setup
		where A.CMS_SO_NO = @PREFIX
		
		select A.CMS_SO_NO, A.DOCNUMBR, A.DOCDATE, A.CMS_SO_FILENAME, A.CMS_SO_FILEPATH, 'ATTACHMENT' DATATYPE
		from CMS01133002C3 A with(nolock) --CMS_SO_DTL_ATTACHMENT
		where A.CMS_SO_NO = @PREFIX
		
		select A.CMS_SO_NO, A.CMS_CONTRACT_NO, A.CUSTNMBR, A.CMS_QUOTATION_NO, A.CMS_QUOTATION_TYPE, A.DOCDATE, A.CMS_DESC CMS_KETERANGAN, A.From_Date, A.TODATE
		, A.CURNCYID, B.CRNCYSYM, A.CMS_DPP DPP, A.CMS_SELECTED, 'QUOTATION' DATATYPE
		from CMS01133003C3 A with(nolock)--CMS_SO_DTL_QUOTATION
		left join DYNAMICS..MC40200 B on B.CURNCYID=A.CURNCYID--Currency Setup
		where A.CMS_SO_NO = @PREFIX
		
		select A.CMS_SO_NO, A.CMS_QUOTATION_NO, A.LNITMSEQ, A.LNSEQNBR, A.CMS_ROUTEID_FROM, A.CMS_ROUTEID_TO, A.CMS_CONT_UKURAN_ID, A.CMS_CONT_UKURAN
		, A.CMS_KETERANGAN, A.CMS_FLAGGING, A.CMS_STUFF_LOCATION, A.QUANTITY, A.UNITPRCE, A.XTNDPRCE, A.SUBTOTAL, A.TAXDTLID, A.TXDTLPCT, A.TAXAMNT
		, A.TOTAL, A.CMS_SELECTED, 'ROUTE' DATATYPE
		from CMS01133004C3 A with(nolock) --CMS_SO_DTL_ROUTE
		where A.CMS_SO_NO = @PREFIX
	
		select A.CMS_SO_NO, A.CMS_QUOTATION_NO, A.LNITMSEQ, A.ITEMNMBR, A.ITEMDESC, A.QUANTITY, A.CHRGAMNT, A.TAXAMNT, A.SUBTOTAL, A.TOTAL, 'CHARGES' DATATYPE
		from CMS01133005C3 A with(nolock) --CMS_SO_DTL_CHARGES
		where A.CMS_SO_NO = @PREFIX

		select A.CMS_SO_NO, A.LNITMSEQ, A.CMS_COMMODITY_DESC, A.UOFM, A.UMDPQTYS, A.QTYSHPPD, A.CMS_WEIGHT, 'COMMODITY' DATATYPE
		from CMS01133006C3 A with(nolock) --CMS_SO_DTL_COMMODITY
		where A.CMS_SO_NO = @PREFIX

		select A.CMS_SO_NO, A.CUSTNMBR, A.DOCNUMBR, A.DSCRIPTN, A.QUANTITY, A.LNITMSEQ, A.CMS_SELECTED, 'DOCCHECKLIST' DATATYPE
		from CMS01133007C3 A with(nolock) --CMS_SO_DTL_DOCCHECKLIST
		where A.CMS_SO_NO = @PREFIX
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000), @ErrorSeverity INT, @ErrorState INT
		SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = ERROR_STATE()
		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState)
	END CATCH
END
GO

/*
	exec CMS_SO_GET_DATA_SALESORDER '','','SO-0623-00003'
	
	select * from CMS01133001C3 --CMS_SO_HEADER
	select * from CMS01133002C3 --CMS_SO_DTL_ATTACHMENT
	select * from CMS01133003C3 --CMS_SO_DTL_QUOTATION
	select * from CMS01133004C3 --CMS_SO_DTL_ROUTE
	select * from CMS01133005C3 --CMS_SO_DTL_CHARGES
	select * from CMS01133006C3 --CMS_SO_DTL_COMMODITY
	select * from CMS01133007C3 --CMS_SO_DTL_DOCCHECKLIST

*/








