CREATE OR ALTER proc CMS_Contract_Save
(  
 @CMS_CONTRACT_NO varchar(21),
 @CMS_CONTRACT_TYPE int,
 @DOCDATE datetime,
 @CMS_SUBMITTED_DATE datetime,
 @From_Date datetime,
 @TODATE datetime,
 @CMS_DURATION int,
 @CURNCYID varchar(15),
 @CRNCYSYM varchar(3),
 @CUSTNMBR varchar(15),
 @CUSTNAME varchar(65),
 @PYMTTYPE int,
 @PYMTRMID varchar(21),
 @PYMNTTRM varchar(15),
 @TAXTYPE int,
 @TAXSCHID varchar(15),
 @TAXDTLID varchar(15),
 @TXDTLPCT int,
 @CMS_ORDER_TYPE int,
 @CMS_KETERANGAN varchar(501),
 @CMS_Status int,
 @USERID varchar(30),
 @CTRROUTE CTRROUTE readonly,
 @CTRCHRGS CTRCHRGS readonly
)  
AS BEGIN  
	BEGIN TRY
		--begin transaction
		--header
		IF EXISTS(select top 1 * from CMS01131001C3 WHERE CMS_CONTRACT_NO=@CMS_CONTRACT_NO)
		BEGIN
			UPDATE CMS01131001C3 SET CMS_CONTRACT_TYPE=@CMS_CONTRACT_TYPE, DOCDATE=@DOCDATE, CMS_SUBMITTED_DATE=@CMS_SUBMITTED_DATE, From_Date=@From_Date, TODATE=@TODATE, 
			CMS_DURATION=@CMS_DURATION, CURNCYID=@CURNCYID, CRNCYSYM=@CRNCYSYM, CUSTNMBR=@CUSTNMBR, CUSTNAME=@CUSTNAME, 
			PYMTTYPE=@PYMTTYPE, PYMTRMID=@PYMTRMID, PYMNTTRM=@PYMNTTRM, TAXTYPE=@TAXTYPE, TAXSCHID=@TAXSCHID, 
			TAXDTLID=@TAXDTLID, TXDTLPCT=@TXDTLPCT, CMS_ORDER_TYPE=@CMS_ORDER_TYPE, CMS_KETERANGAN=@CMS_KETERANGAN, CMS_Status=@CMS_Status, 
			MDFUSRID=@USERID, MODIFDT=CAST(GETDATE() as date), MODIFTIME=CAST(GETDATE() as time)
			WHERE CMS_CONTRACT_NO=@CMS_CONTRACT_NO
		END
		ELSE 
		BEGIN
			insert into CMS01131001C3(CMS_CONTRACT_NO, CMS_CONTRACT_TYPE, DOCDATE, CMS_SUBMITTED_DATE, From_Date, TODATE, CMS_DURATION, CURNCYID, CRNCYSYM, CUSTNMBR, CUSTNAME, 
			PYMTTYPE, PYMTRMID, PYMNTTRM, TAXTYPE, TAXSCHID, TAXDTLID, TXDTLPCT, CMS_ORDER_TYPE, CMS_KETERANGAN, CMS_Status, CRUSRID, CREATDDT, CREATETIME, MDFUSRID, MODIFDT, MODIFTIME)
			values
			(@CMS_CONTRACT_NO, @CMS_CONTRACT_TYPE, @DOCDATE, @CMS_SUBMITTED_DATE, @From_Date, @TODATE, @CMS_DURATION, @CURNCYID, @CRNCYSYM, @CUSTNMBR, @CUSTNAME, 
			@PYMTTYPE, @PYMTRMID, @PYMNTTRM, @TAXTYPE, @TAXSCHID, @TAXDTLID, @TXDTLPCT, @CMS_ORDER_TYPE, @CMS_KETERANGAN, @CMS_Status, @USERID, CAST(GETDATE() as date), CAST(GETDATE() as time),
			@USERID, CAST(GETDATE() as date), CAST(GETDATE() as time))
		END
		
		--detail route
		delete from CMS01131002C3 where RTRIM(CMS_CONTRACT_NO)=RTRIM(@CMS_CONTRACT_NO)

		insert into CMS01131002C3(CMS_CONTRACT_NO, LNITMSEQ, LNSEQNBR, CMS_ROUTEID_FROM, CMS_ROUTEID_TO, CMS_CONT_UKURAN_ID, CMS_CONT_UKURAN, CMS_KETERANGAN, 
		CMS_STUFF_LOCATION, QUANTITY, UNITPRCE, XTNDPRCE, SUBTOTAL, TAXDTLID, TXDTLPCT, TAXAMNT, TOTAL)
		select distinct CMS_CONTRACT_NO, LNITMSEQ, LNSEQNBR, CMS_ROUTEID_FROM, CMS_ROUTEID_TO, CMS_CONT_UKURAN_ID, CMS_CONT_UKURAN, CMS_KETERANGAN, 
		CMS_STUFF_LOCATION, QUANTITY, UNITPRCE, XTNDPRCE, SUBTOTAL, TAXDTLID, TXDTLPCT, TAXAMNT, TOTAL
		from @CTRROUTE

		/* cursor
		declare @CMS_CONTRACT_NO2 varchar(21), @LNITMSEQ int, @LNSEQNBR numeric(19,5), @CMS_ROUTEID_FROM varchar(21), @CMS_ROUTEID_TO varchar(21), @CMS_CONT_UKURAN_ID varchar(25), 
		@CMS_CONT_UKURAN varchar(51), @CMS_KETERANGAN2 varchar(501), @CMS_STUFF_LOCATION varchar(101), @QUANTITY numeric(19,5), @UNITPRCE numeric(19,5), @XTNDPRCE numeric(19,5), 
		@SUBTOTAL numeric(19,5), @TAXDTLID2 varchar(15), @TXDTLPCT2 numeric(19,5), @TAXAMNT numeric(19,5), @TOTAL numeric(19,5)

		declare ROUTE_Cursor cursor for
		
		select distinct * from @CTRROUTE

		open ROUTE_Cursor

		fetch next from ROUTE_Cursor into @CMS_CONTRACT_NO2, @LNITMSEQ, @LNSEQNBR, @CMS_ROUTEID_FROM, @CMS_ROUTEID_TO, @CMS_CONT_UKURAN_ID, @CMS_CONT_UKURAN, 
				@CMS_KETERANGAN2, @CMS_STUFF_LOCATION, @QUANTITY, @UNITPRCE, @XTNDPRCE, @SUBTOTAL, @TAXDTLID2, @TXDTLPCT2, @TAXAMNT, @TOTAL

		WHILE (@@FETCH_STATUS=0) BEGIN

			insert into CMS01131002C3(CMS_CONTRACT_NO, LNITMSEQ, LNSEQNBR, CMS_ROUTEID_FROM, CMS_ROUTEID_TO, CMS_CONT_UKURAN_ID, CMS_CONT_UKURAN, CMS_KETERANGAN, 
			CMS_STUFF_LOCATION, QUANTITY, UNITPRCE, XTNDPRCE, SUBTOTAL, TAXDTLID, TXDTLPCT, TAXAMNT, TOTAL)
			values
			(select)

			fetch next from tblscdtl into @CMS_CONTRACT_NO2, @LNITMSEQ, @LNSEQNBR, @CMS_ROUTEID_FROM, @CMS_ROUTEID_TO, @CMS_CONT_UKURAN_ID, @CMS_CONT_UKURAN, 
					@CMS_KETERANGAN2, @CMS_STUFF_LOCATION, @QUANTITY, @UNITPRCE, @XTNDPRCE, @SUBTOTAL, @TAXDTLID2, @TXDTLPCT2, @TAXAMNT, @TOTAL
		END  

		close ROUTE_Cursor  
		deallocate ROUTE_Cursor  
		*/
		--detail charges

		delete from CMS01131003C3 where RTRIM(CMS_CONTRACT_NO)=RTRIM(@CMS_CONTRACT_NO)

		insert into CMS01131003C3(CMS_CONTRACT_NO, LNITMSEQ, ITEMNMBR, ITEMDESC, QUANTITY, CHRGAMNT, TAXAMNT, SUBTOTAL, TOTAL)
		select distinct CMS_CONTRACT_NO, LNITMSEQ, ITEMNMBR, ITEMDESC, QUANTITY, CHRGAMNT, TAXAMNT, SUBTOTAL, TOTAL 
		from @CTRCHRGS
	--commit
	END TRY
	BEGIN CATCH
		--rollback
		DECLARE @ErrorMessage NVARCHAR(4000)
		DECLARE @ErrorSeverity INT
		DECLARE @ErrorState INT

		SELECT @ErrorMessage = ERROR_MESSAGE(),
			   @ErrorSeverity = ERROR_SEVERITY(),
			   @ErrorState = ERROR_STATE()

		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState)
		select @ErrorMessage as output
	END CATCH 
END  
/*  

declare @p23 dbo.CTRROUTE
insert into @p23 values(N'CONTRACT/ID/00002',16384,0,N'JKT',N'RUTE2',N'20Dry',N'20Dry',N'test1',N'tester stuff 1',50,10000000,500000000,50,N'600000000',0,0,600000000)
insert into @p23 values(N'CONTRACT/ID/00002',16384,16384,N'JKT',N'RUTE2',N'20Dry',N'20Dry',N'test1.1',N'tester stuff 1.1',50,10000000,500000000,50,N'600000000',0,0,600000000)
insert into @p23 values(N'CONTRACT/ID/00002',32768,0,N'AMBON',N'RUTE3',N'40RF',N'40RF',N'test2',N'tester stuff 2',20,5000000,100000000,20,N'600000000',0,0,600000000)
insert into @p23 values(N'CONTRACT/ID/00002',32768,16384,N'AMBON',N'RUTE3',N'40RF',N'40RF',N'test2.1',N'tester stuff 2.1',20,5000000,100000000,20,N'600000000',0,0,600000000)

declare @p24 dbo.CTRCHRGS
insert into @p24 values(N'CONTRACT/ID/00002',16384,N'AGENT-BURU',N'tester',10,25000000,250000,25250000,25250000)

exec CMS_Contract_Save @CMS_CONTRACT_NO=N'CONTRACT/ID/00002',@CMS_CONTRACT_TYPE=1,@DOCDATE='2023-05-27 00:00:00',@CMS_SUBMITTED_DATE='2023-05-27 00:00:00',
@From_Date='2023-06-01 00:00:00',@TODATE='2023-06-30 00:00:00',@CMS_DURATION=29,@CURNCYID=N'IDR',@CRNCYSYM=N'Rp',@CUSTNMBR=N'AAR',@CUSTNAME=N'ALI ARRIDHO',
@PYMTTYPE=2,@PYMTRMID=N'14 Days',@PYMNTTRM=N'14 Days',@TAXTYPE=1,@TAXSCHID=N'VAT OUT 1%',@TAXDTLID=N'VAT OUT 1%',@TXDTLPCT=1,@CMS_ORDER_TYPE=1,@CMS_KETERANGAN=N'tester',
@CMS_Status=1,@USERID=N'teg01          ',@CTRROUTE=@p23,@CTRCHRGS=@p24

*/
GO