CREATE OR ALTER proc [dbo].[Insert_Error_Logs]
(
@MethodName varchar(MAX),
@USERID varchar(30),
@INTERID varchar(30),
@LogDateTime varchar(50),
@Message varchar(MAX)
)
AS
BEGIN
	INSERT INTO PWO0103200800(MethodName, email, LogDateTime, Message)
	values(@MethodName, @USERID, @LogDateTime, @Message)

	DECLARE	@ID INT
	DECLARE @CNT INT=0, @LOGMAXRECORD INT=1000000000, @TOBEDELETED INT=0, @DEX_ROW_ID INT=0

	SELECT @CNT = COUNT(1) FROM PWO0103200800 WITH(NOLOCK)

	IF @CNT IS NULL SELECT @CNT = 0

	SELECT @TOBEDELETED = CASE WHEN @CNT-@LOGMAXRECORD > 0 THEN @CNT-@LOGMAXRECORD ELSE 0 END

	SELECT @DEX_ROW_ID=MAX(DEX_ROW_ID) FROM (SELECT TOP(@TOBEDELETED) DEX_ROW_ID FROM PWO0103200800 ORDER BY DEX_ROW_ID)A

	IF @DEX_ROW_ID IS NULL SELECT @DEX_ROW_ID=0

	DELETE PWO0103200800 WHERE DEX_ROW_ID<=@DEX_ROW_ID
END
/*
exec [Insert_Error_Logs] '1234'
*/
GO