IF EXISTS (SELECT * FROM sys.types WHERE is_user_defined = 1 AND name = 'DTCONTAINERDTL')
BEGIN
	DROP TYPE [dbo].[DTCONTAINERDTL]
END
GO

CREATE TYPE [dbo].[DTCONTAINERDTL] AS TABLE(
	[LNITMSEQ] [int] NULL,
	[CONTRACT_NO] [char](51) NULL,
	[DESCRIPTION] [char](51) NULL
)
GO